### PR TITLE
Set up files for CI

### PR DESCRIPTION
**Pull request by elabandari**
Hey folks,
 
This turned into a pretty big PR. I am editing this description to summarize the changes that were made to allow for continuous integration and better quality and more reproducible code: 

1. All the raw data used was moved to the `inst/extdata` directory and referred to using robust filepaths. 
2. Emailer function has been rewritten without mailR (which means we no longer need rJava as a dependency)
3. Code has been styled and missing dependencies were added.
4. As Craigslist can detect bot scraping activity and throws a 403 in response, we made the decision to skip the live scraping on continuous integration. These tests will still run on your local machine. This means our code coverage is a lot lower than what it would be if this feature was on but this was a necessary trade-off for implementing CI. 

Cheers, 
Ela

### CODE REVIEW

**Comment by elabandari** [comment]
**A note about test coverage:**

We had to make some adjustments to the tests for the scraper function so they would run with continuous integration (CI), these are outlined below:

1. Since Craigslist is not very friendly to being scraped, our R-CMD Windows and Ubuntu checks would fail on CI as it would encounter a 403 since Craiglist can detect scraping from the cloud. This issue did not occur locally on any of our computers, therefore, we decided to add the syntax that would skip these tests on CI. This significantly reduced our test coverage.
2. Furthermore, because the GitHub CI cannot scrape data live we had to change our scraper function's example to scraping locally saved data under the inst/exdata directory.

**Comment by elabandari** [comment]
Hi Team, 

After quite a bit of troubleshooting. It seemed a lot cleaner to rewrite the emailer function without mailR and the rJava dependency so this commit includes the rewriting of the emailer function and parts of its tests. All tests are now passing and continuous integration is working 🎉 .

Best, 
Ela

**Comment by elabandari** [comment]
Hi folks! 

The last change I made in this PR was moving all of our raw data files to the `inst/extdata` directory and passing the robust file paths into all of our tests. Now our package should be looking a lot cleaner :smile_cat: 

Good night~

**Review by athy9193 — APPROVED** [review]
Great works @elabandari! Thank you! :)

**Pull request merged**
